### ISSUE TITLE
Complete installation procedure, how to solve No module named 'torch'

### ISSUE THREAD

**Issue by shodanx2** [VAST-AI-Research/TripoSR#40]
As discussed in https://github.com/tatsy/torchmcubes/issues/5

Here is the complete solution to install TripoSR

Install python  https://www.python.org/ftp/python/3.12.2/python-3.12.2-amd64.exe
Install rust package manager https://win.rustup.rs/x86_64
Install Visual Studio Community https://visualstudio.microsoft.com/visual-cpp-build-tools/  
Include "Desktop C++" workload and the buildtools (should be selected by default)
download triposr https://github.com/VAST-AI-Research/TripoSR/archive/refs/heads/main.zip
uncompress with tar -xf TripoSR-main.zip

You'll want to restart your computer or at least your terminal here

Now run, in a console, in the folder TripoSR-main

```
pip install --upgrade setuptools
pip install wheel
pip install ninja
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
pip install -r requirements.txt
```

Finally test triposr with 

`python run.py examples/chair.png --output-dir output/`

This should get you a chair like this

![image](https://github.com/VAST-AI-Research/TripoSR/assets/10621885/541e9093-29b7-463d-8cc2-03f612c85131)

For viewing OBJ files, you can use 
https://www.meshlab.net/
or 
https://sourceforge.net/projects/glc-player/

You can then try installing gradio, but that did not work for me at the moment due to a pip problem 

![image](https://github.com/VAST-AI-Research/TripoSR/assets/10621885/8892c044-2d78-4be5-aa7b-372f4b73ef22)

**Comment by mirinaeman** [comment]
Building wheels for collected packages: torchmcubes, tokenizers
  Building wheel for torchmcubes (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]

**Comment by bennyguo** [comment]
@diego-lipinski-de-castro Could you please give the error messages? I can successfully run on my M1 Mac.

**Comment by bennyguo** [comment]
@mirinaeman Could you please try cloning https://github.com/tatsy/torchmcubes.git to a local directory, enter the cloned directory, and do `pip install -v .`? This will give more thorough error messages if it does not build.

**Comment by zubairhamed** [comment]
I'm getting the same error. ModuleNotFound

Processing d:\projects\gh\torchmcubes
  Running command pip subprocess to install build dependencies
  Collecting setuptools>=40.8.0
    Using cached setuptools-69.1.1-py3-none-any.whl.metadata (6.2 kB)
  Using cached setuptools-69.1.1-py3-none-any.whl (819 kB)
  Installing collected packages: setuptools
  Successfully installed setuptools-69.1.1
  Installing build dependencies ... done
  Running command Getting requirements to build wheel
  Traceback (most recent call last):
    File "C:\Users\zubai\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
      main()
    File "C:\Users\zubai\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\zubai\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
             ^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\zubai\AppData\Local\Temp\pip-build-env-8ku58s29\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\zubai\AppData\Local\Temp\pip-build-env-8ku58s29\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
      self.run_setup()
    File "C:\Users\zubai\AppData\Local\Temp\pip-build-env-8ku58s29\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
      super().run_setup(setup_script=setup_script)
    File "C:\Users\zubai\AppData\Local\Temp\pip-build-env-8ku58s29\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
      exec(code, locals())
    File "<string>", line 2, in <module>
  ModuleNotFoundError: No module named 'torch'
  error: subprocess-exited-with-error

**Comment by shodanx2** [comment]
Installing MS Visual Studio with the Desktop C++ workload was how I solved this issue. 
Let me know if there is a way to resolve this without installing that huge thing. 
Preferably, without even having to click a "I agree"  box

**Comment by zubairhamed** [comment]
@shodanx2  Ok i had installed prior to this VC++ toolchain but didn't work. However i ran your pip install manually and that worked.

**Comment by pookiefoof** [comment]
> Installing MS Visual Studio with the Desktop C++ workload was how I solved this issue. Let me know if there is a way to resolve this without installing that huge thing. Preferably, without even having to click a "I agree" box

Installing torchmcubes requires C++ build toolchains, so on Windows installing MSVC actually might be the easiest way.

**Comment by Xiuzhenpeng** [comment]
> As discussed in [tatsy/torchmcubes#5](https://github.com/tatsy/torchmcubes/issues/5) [tatsy/torchmcubes#5](https://github.com/tatsy/torchmcubes/issues/5) 正如
> 
> Here is the complete solution to install TripoSR这是安装TripoSR的完整解决方案
> 
> Install python https://www.python.org/ftp/python/3.12.2/python-3.12.2-amd64.exe安装 python https://www.python.org/ftp/python/3.12.2/python-3.12.2-amd64.exe Install rust package manager https://win.rustup.rs/x86_64安装 rust 包管理器 https://win.rustup.rs/x86_64 Install Visual Studio Community https://visualstudio.microsoft.com/visual-cpp-build-tools/安装 Visual Studio Community https://visualstudio.microsoft.com/visual-cpp-build-tools/ Include "Desktop C++" workload and the buildtools (should be selected by default)包括“桌面 C++”工作负载和构建工具（应默认选中） download triposr https://github.com/VAST-AI-Research/TripoSR/archive/refs/heads/main.zip下载 Triposr https://github.com/VAST-AI-Research/TripoSR/archive/refs/heads/main.zip uncompress with tar -xf TripoSR-main.zip使用 tar -xf TripoSR-main.zip 解压缩
> 
> You'll want to restart your computer or at least your terminal here您需要在此处重新启动计算机或至少重新启动终端
> 
> Now run, in a console, in the folder TripoSR-main现在，在控制台中，在 TripoSR-main 文件夹中运行
> 
> ```
> pip install --upgrade setuptools
> pip install wheel
> pip install ninja
> pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
> pip install -r requirements.txt
> ```
> 
> Finally test triposr with最后测试triposr
> 
> `python run.py examples/chair.png --output-dir output/`
> 
> This should get you a chair like this这应该会给你一把这样的椅子
> 
> ![image](https://private-user-images.githubusercontent.com/10621885/311187348-541e9093-29b7-463d-8cc2-03f612c85131.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNTkyMjUsIm5iZiI6MTcxODE1ODkyNSwicGF0aCI6Ii8xMDYyMTg4NS8zMTExODczNDgtNTQxZTkwOTMtMjliNy00NjNkLThjYzItMDNmNjEyYzg1MTMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDAyMjIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyZDI0YzY5MzQxNmVjYmY5N2FiZmFiN2MxOGZjMDcyZmU5NDY2YzQyZjQ3OWVkMThjOTZmMmQyOTljMGRkOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ay6fKuMbu_aIWnk6B2xX5powr1wZCp0uxU3hNnY11DA)
> 
> For viewing OBJ files, you can use要查看 OBJ 文件，您可以使用 https://www.meshlab.net/ or 或 https://sourceforge.net/projects/glc-player/
> 
> You can then try installing gradio, but that did not work for me at the moment due to a pip problem然后您可以尝试安装 gradio，但由于 pip 问题，目前对我不起作用
> 
> ![image](https://private-user-images.githubusercontent.com/10621885/311187733-8892c044-2d78-4be5-aa7b-372f4b73ef22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNTkyMjUsIm5iZiI6MTcxODE1ODkyNSwicGF0aCI6Ii8xMDYyMTg4NS8zMTExODc3MzMtODg5MmMwNDQtMmQ3OC00YmU1LWFhN2ItMzcyZjRiNzNlZjIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDAyMjIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1YzI1YzJkZTAwZjZmOTRkZTAxZThmYTZjNDNlZmMwZDIxZDI1MTJjNDU3ZWIzZmRhZmM2ZTdlODljOGE5YTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2lcqDN83vtoejylQcePrIUsSz9cBwRH0VSZO7pcrODY)

I donnot know to install wheel and ninja. Now i have fix this problem. Thank you very much
