### ISSUE TITLE
two important points in 3d gen-or-recon

### ISSUE THREAD

**Issue by yuedajiong** [VAST-AI-Research/TripoSR#47]
1) representation 表达
    TripoSR的大牛用的triplane作为输入极简的表示，然后扩展到10层的NeRF-MLP中。
    https://github.com/WU-CVGL/MVControl-threestudio/issues/5 核心：无论gspoints/GS还是mesh/FlexiCubes那种多视图强拟合的，基于梯度甚至直接增减点的优势，在偏forward gen的流程中，优势利用不上了。
    TGS是hybrid triplane gauss.   https://zouzx.github.io/TriplaneGaussian/

2) camera pose 相机
    训练部分，如果是在3D对象上训练的，这个本来很难处理的问题，在这个算法定义的任务里就不存在。但camera-pose其实很重要。

我把我读到的主要的做法，包括表示和相机，写在这里了。（可能一下不是很全，后续可能更新）
https://github.com/yuedajiong/super-ai/blob/main/superai-20240310-3d-reconstruction-two-important-representation-and-camerapose.txt

另外：关于本文这个网络的图，标注了一下。感觉要在2D上监督，也就是要给出相机位置渲染出图片后做loss。 网络结构上NeRF的10层感觉好深，因为每次forward后，在triplane之后的MLP都要给出很多camera-pose去render，这里网络越深越慢。  第一是不知道这里多浅足够表示不同对象和场景；第二是几乎没有看到有文章研究什么网络最合适NeRF的MLP替代。
有一些疑问：1)learnable pos embed到底作用是什么，因为是一个与输入无关的东西，训练完后不就固定了吗？OpenLRM中也是一样的逻辑，名字pos_embed； 2)把输入图像的信息浓缩到triplane然后在放到一个不浅的MLP中，这样是不是导致就最终很难还原度很高的去利用输入图像。
![image](https://github.com/VAST-AI-Research/TripoSR/assets/52232153/a92bf233-9c41-46e0-bfd9-9df4c1f7b861)

**Comment by yuedajiong** [comment]
除了LRM等，现很多算法网络大的环节差不多，比如Leap:

1.  选择一个A-"立体表示"（隐式还是显示，支持3D还支持4D不，...)；和对应的B-"可微渲染"。
2.  决定在那个空间构造损失：C-"2D/3D-Loss"，和选择对应数据集。
3. 构建网络的pipeline，基本结构：D-"ViT转换图片；Transformer/Diffusion/UNet等长长的记忆/变换网络；转换到选定的立体表示；用已知或者估计的相机参数渲染<极少算法这一步完全不用相机参数，也有，极少>；算损失完毕“。

![image](https://github.com/VAST-AI-Research/TripoSR/assets/52232153/86256c4a-6c27-4eca-bb5a-091423640007)

**Comment by bennyguo** [comment]
Please use the discussion panel for this, thanks!
