### ISSUE TITLE
Training Collaboration, Win-Win.

### ISSUE THREAD

**Issue by yuedajiong** [VAST-AI-Research/TripoSR#75]
I provide all "one-click-to-train" code.
Is anyone willing to provide computing power to collaborate on large-scale training together?

# Costs:
    computing:
        4+ A100  (estimated，maybe more)
    storage:
        64T+ (estimated, maybe more) 
        for objvaserse download, and multi-view rendering;  and image-features cache.

# Profits:
    model weights
    all code, no limits
    SOTA algorithms (various enhancements: image-feature-cache, fixed-and-generalized parameterd renderer, different priori source, priori hash/knn retrieval, equivariant-stereo-representation, loss-on-'pure'-2D(pure means without any camera-pose), ...)

small-scaling training screen-capturing:
![image](https://github.com/VAST-AI-Research/TripoSR/assets/52232153/670a5690-c913-455a-b231-ad634fd833a5)

**Comment by Danil-Shishkhanov** [comment]
@yuedajiong we've seen your message about providing computing power to collaborate on large-scale training together.
We've also seen your work here on github, and we'd like to collaborate with you, and yes we can provide computing power.
Are you still interested?
