### ISSUE TITLE
 Running command git clone --filter=blob:none --quiet https://github.com/tatsy/torchmcubes.git 

### ISSUE THREAD

**Issue by tiandaoyuxi** [VAST-AI-Research/TripoSR#9]
(venv) D:\TripoSR>pip install -r requirements.txt
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting git+https://github.com/tatsy/torchmcubes.git (from -r requirements.txt (line 4))
  Cloning https://github.com/tatsy/torchmcubes.git to c:\users\ws3-01\appdata\local\temp\pip-req-build-e6vgr7zd
  Running command git clone --filter=blob:none --quiet https://github.com/tatsy/torchmcubes.git 'C:\Users\ws3-01\AppData\Local\Temp\pip-req-build-e6vgr7zd'
  Resolved https://github.com/tatsy/torchmcubes.git to commit 3aef8afa5f21b113afc4f4ea148baee850cbd472
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "D:\TripoSR\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "D:\TripoSR\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "D:\TripoSR\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\ws3-01\AppData\Local\Temp\pip-build-env-jbmzoijq\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\ws3-01\AppData\Local\Temp\pip-build-env-jbmzoijq\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\ws3-01\AppData\Local\Temp\pip-build-env-jbmzoijq\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\ws3-01\AppData\Local\Temp\pip-build-env-jbmzoijq\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 2, in <module>
      ModuleNotFoundError: No module named 'torch'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by runshengdu** [comment]
pip install wheel setuptools pip --upgrade

**Comment by tiandaoyuxi** [comment]
> (venv) D:\TripoSR>pip install -r requirements.txt Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com Collecting git+https://github.com/tatsy/torchmcubes.git (from -r requirements.txt (line 4)) Cloning https://github.com/tatsy/torchmcubes.git to c:\users\ws3-01\appdata\local\temp\pip-req-build-e6vgr7zd Running command git clone --filter=blob:none --quiet https://github.com/tatsy/torchmcubes.git 'C:\Users\ws3-01\AppData\Local\Temp\pip-req-build-e6vgr7zd' Resolved https://github.com/tatsy/torchmcubes.git to commit 3aef8afa5f21b113afc4f4ea148baee850cbd472 Installing build dependencies ... done Getting requirements to build wheel ... error error: subprocess-exited-with-error
> 
> × Getting requirements to build wheel did not run successfully. │ exit code: 1 ╰─> [17 lines of output] Traceback (most recent call last): File "D:\TripoSR\venv\lib\site-packages\pip_vendor\pyproject_hooks_in_process_in_process.py", line 353, in main() File "D:\TripoSR\venv\lib\site-packages\pip_vendor\pyproject_hooks_in_process_in_process.py", line 335, in main json_out['return_val'] = hook(**hook_input['kwargs']) File "D:\TripoSR\venv\lib\site-packages\pip_vendor\pyproject_hooks_in_process_in_process.py", line 118, in get_requires_for_build_wheel return hook(config_settings) File "C:\Users\ws3-01\AppData\Local\Temp\pip-build-env-jbmzoijq\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel return self._get_build_requires(config_settings, requirements=['wheel']) File "C:\Users\ws3-01\AppData\Local\Temp\pip-build-env-jbmzoijq\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires self.run_setup() File "C:\Users\ws3-01\AppData\Local\Temp\pip-build-env-jbmzoijq\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup super().run_setup(setup_script=setup_script) File "C:\Users\ws3-01\AppData\Local\Temp\pip-build-env-jbmzoijq\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup exec(code, locals()) File "", line 2, in ModuleNotFoundError: No module named 'torch' [end of output]
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. error: subprocess-exited-with-error
> 
> × Getting requirements to build wheel did not run successfully. │ exit code: 1 ╰─> See above for output.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip.



> pip install wheel setuptools pip --upgrade

**Comment by tiandaoyuxi** [comment]
> pip install wheel setuptools pip --upgrade

THX！ cool！
