### ISSUE TITLE
I Tried to use the --bake-texture parameter, but the answer is as follows:

### ISSUE THREAD

**Issue by Manursp0022** [VAST-AI-Research/TripoSR#98]
<img width="1425" alt="Problems" src="https://github.com/VAST-AI-Research/TripoSR/assets/114728100/cc77254b-b2b3-4fc9-84ea-7ccb20f9af1d">

**Comment by MProductionsmado** [comment]
have the same issue

**Comment by st-projects-00** [comment]
to be helpful, I ran into the same issue. on ubuntu did the following to fix it:
sudo apt-get install xvfb
xvfb-run yourpythonapp.py --pythonappargs... --headless
no guarantees this will work in all cases but it did for me as x windows is not installed in my build. can also try without --headless
