### ISSUE TITLE
Is TripoSR using the latest code from tripo3d.ai ?

### ISSUE THREAD

**Issue by hypervoxel** [VAST-AI-Research/TripoSR#99]
Is TripoSR using the latest code from tripo3d.ai ?

There seems to have been some improvement to tripo3d.ai recently and I wondered if they are being reflected in TripoSR ?

Have there been recent updates or improvements to TripoSR's 2d to 3d model ?

**Comment by mrbid** [comment]
Imagine that the SR part in TripoSR stands for "Sample Release". Then you have your answer.

**Comment by hypervoxel** [comment]
Thank you for the reply. Do you know when / if TripoSR will be updated?

**Comment by mrbid** [comment]
> Thank you for the reply. Do you know when / if TripoSR will be updated?

They are never going to give away their latest SOTA model as it is a commercial product, if they will update the model in TripoSR with something a little better that depends on the competition, at the moment TripoSR is the best open source model, unless a competitor releases a better open source model for a different project, then they have no incentive to release another model for TripoSR. Even so, they would just release a model a little better than their competitor had and nothing close to their commercial model.

**Comment by hypervoxel** [comment]
I have found that CRM is better than TripoSR

**Comment by hypervoxel** [comment]
It looks like TripoSR has been updated with higher resolution textures and higher resolution marking cubes (1024), can anyone confirm?

**Comment by pookiefoof** [comment]
> It looks like TripoSR has been updated with higher resolution textures and higher resolution marking cubes (1024), can anyone confirm?

Yes! TripoSR now supports exporting mesh textures.

**Comment by 3blackbar** [comment]
> > It looks like TripoSR has been updated with higher resolution textures and higher resolution marking cubes (1024), can anyone confirm?
> 
> Yes! TripoSR now supports exporting mesh textures.

There was no TripoSR update ! THe website called tripoai is not the same as this repository ! Stop confusing people. 
TripoSR was released few months ago and till this day there was no update to the weights code.

**Comment by pookiefoof** [comment]
We are not trying to confuse people.
With PR#94 https://github.com/VAST-AI-Research/TripoSR/pull/94, TripoSR can export textured meshes.

**Comment by pookiefoof** [comment]
> > > It looks like TripoSR has been updated with higher resolution textures and higher resolution marking cubes (1024), can anyone confirm?
> > 
> > 
> > Yes! TripoSR now supports exporting mesh textures.
> 
> There was no TripoSR update ! THe website called tripoai is not the same as this repository ! Stop confusing people. TripoSR was released few months ago and till this day there was no update to the weights code.

We are not trying to confuse people.
With PR#94 https://github.com/VAST-AI-Research/TripoSR/pull/94, TripoSR can export textured meshes.

**Comment by JohnG0024** [comment]
@hypervoxel You sure CRM is better than tripo3d? @mrbid It's been couple months now, is tripo3d still the best in competition?

**Comment by mrbid** [comment]
> @hypervoxel You sure CRM is better than tripo3d? @mrbid It's been couple months now, is tripo3d still the best in competition?

I suppose that is for you to judge, but it would seem CRM is still slower than TripoSR which means if operating costs mean anything to you that's a factor of importance, as for quality that's always going to be subjective.

But yes I think TripoSR in most cases has better quality output models than CRM.
